/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ph.com.fsoft.temp.service.blue.repository;

import java.util.stream.Stream;
import org.springframework.data.repository.PagingAndSortingRepository;
import org.springframework.data.repository.query.Param;
import org.springframework.stereotype.Repository;
import ph.com.fsoft.temp.service.blue.model.domain.Person;

/**
 * Uses Spring Data, very magical :). No JPQL or SQL thingy. JPQL query is
 * generated by Spring.
 *
 * @author warren.nocos
 */
@Repository
public interface PersonRepository extends PagingAndSortingRepository<Person, Long> {

    Stream<Person> findByLastName(@Param("firstName") String firstName);

}
